using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CoreRPC.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class ProxyGenerator : IIncrementalGenerator
{
    private record ServiceMethodModel(string Name, string ReturnType, EquatableList<string> Parameters);
    private record ServiceModel(string Name, string Namespace, EquatableList<ServiceMethodModel> Methods);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var all = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: "CoreRPC.RpcServiceAttribute",
                predicate: (node, _) => node is InterfaceDeclarationSyntax,
                TransformInterfaceModels);

        context.RegisterSourceOutput(all, static (context, service) =>
        {
            var classBuilder = new StringBuilder();
            classBuilder.AppendLine("""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ProxyGenerator source generator.
// </auto-generated>
//------------------------------------------------------------------------------
""");
            classBuilder.AppendLine("using System;");
            classBuilder.AppendLine("using System.Reflection;");
            classBuilder.AppendLine("using CoreRPC.CodeGen;");
            classBuilder.AppendLine();

            var proxiesNamespace = "CorePRC.Generated";
            var proxyName = service.Name + "Proxy";
            var proxyFullName = proxiesNamespace + "." + proxyName;
            var interfaceFullName = service.Namespace is { } ns ? ns + "." + service.Name : service.Name;

            classBuilder
                .Append("[assembly: CoreRPC.RpcServiceProxyAttribute<").Append(interfaceFullName).Append(">(typeof(").Append(proxyFullName).AppendLine("))]");

            classBuilder
                .AppendLine()
                .Append("namespace ")
                .AppendLine(proxiesNamespace)
                .AppendLine("{");

            classBuilder
                .Append("\tinternal sealed class ").Append(proxyName).Append(" : ").AppendLine(interfaceFullName)
                .AppendLine("\t{");

            // fields
            classBuilder
                .AppendLine("\t\tprivate readonly IRealProxy _proxy;");

            foreach (var method in service.Methods)
            {
                classBuilder
                    .Append("\t\tprivate readonly MethodInfo _method_")
                    .Append(method.Name)
                    .AppendLine(";");
            }

            // constructor
            classBuilder
                .Append("\t\tpublic ").Append(proxyName).AppendLine("(IRealProxy proxy)")
                .AppendLine("\t\t{");

            classBuilder
                .AppendLine("\t\t\t_proxy = proxy;")
                .Append("\t\t\tvar type = typeof(").Append(interfaceFullName).AppendLine(");");

            foreach (var method in service.Methods)
            {
                classBuilder
                    .Append("\t\t\t_method_").Append(method.Name).Append(" = type.GetMethod(\"").Append(method.Name)
                    .AppendLine("\")!;");
            }

            classBuilder
                .AppendLine("\t\t}");

            // method implementations
            foreach (var method in service.Methods)
            {
                classBuilder
                    .Append("\t\tpublic ")
                    .Append(method.ReturnType)
                    .Append(" ")
                    .Append(method.Name)
                    .Append("(");

                for (var index = 0; index < method.Parameters.Count; index++)
                {
                    var parameter = method.Parameters[index];
                    if (index != 0) classBuilder.Append(", ");
                    classBuilder.Append(parameter).Append(" P_").Append(index);
                }

                classBuilder
                    .AppendLine(")")
                    .AppendLine("\t\t{");

                classBuilder
                    .AppendLine("\t\t\tvar list = new System.Collections.Generic.List<object>();");

                for (var index = 0; index < method.Parameters.Count; index++)
                {
                    classBuilder.Append("\t\t\tlist.Add(P_").Append(index).AppendLine(");");
                }

                var typeWithoutTask = method.ReturnType;
                if (typeWithoutTask.StartsWith("System.Threading.Tasks.Task<"))
                {
                    typeWithoutTask = typeWithoutTask.Substring("System.Threading.Tasks.Task<".Length);
                    typeWithoutTask = typeWithoutTask.Substring(0, typeWithoutTask.Length - 1);
                }

                classBuilder
                    .Append("\t\t\treturn _proxy.Invoke<")
                    .Append(typeWithoutTask)
                    .Append(">(")
                    .Append("_method_").Append(method.Name).AppendLine(", list);");

                classBuilder
                    .AppendLine("\t\t}");
            }

            classBuilder
                .AppendLine("\t}")
                .AppendLine("}");

            context.AddSource(service.Name + ".Proxy.g.cs", classBuilder.ToString());
        });
    }

    private static ServiceModel TransformInterfaceModels(GeneratorAttributeSyntaxContext ctx, CancellationToken _)
    {
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var node = (InterfaceDeclarationSyntax)ctx.TargetNode;

        var methods = new EquatableList<ServiceMethodModel>();
        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is IMethodSymbol method)
            {
                var parameters = new EquatableList<string>();
                foreach (var parameter in method.Parameters)
                {
                    parameters.Add(parameter.Type.ToString());
                }

                methods.Add(new ServiceMethodModel(method.MetadataName, method.ReturnType.ToString(), parameters));
            }
        }

        var interfaceNamespace = typeSymbol.ContainingNamespace.ToDisplayString() is { } ns && ns != "<global namespace>" ? ns : null;
        return new ServiceModel(typeSymbol.Name, interfaceNamespace, methods);
    }
}