<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoreRPC.AspNetCore\CoreRPC.AspNetCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>
